services:
  app:
    build:
      context: .
      dockerfile: .dockerfile/dev.dockerfile
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      APP_NAME: "To-Do List"
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      APP_KEY: base64:6t8BjEsNSZWl2y+xgepLcLkxOUaS4mtI1cr1Apbt0vA=
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      QUEUE_CONNECTION: database
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MAIL_MAILER: smtp
      MAIL_FROM_ADDRESS: todo@example.com
      MAIL_FROM_NAME: "To-Do List"
      MAIL_RETRY_ATTEMPTS: 3
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      SHARE_LINK_EXPIRATION: 1440
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: todo_app
      DB_USERNAME: todo_user
      DB_PASSWORD: secret
      RUN_MIGRATIONS: true

  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: todo-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data: